# Generated by Django 4.1.7 on 2023-04-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sexe',
            field=models.CharField(default=None, max_length=1),
        ),
    ]
