# Generated by Django 4.1.7 on 2023-04-05 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receptionspace', '0002_patient_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.DecimalField(decimal_places=2, max_digits=5)),
                ('masse', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3)),
                ('motifs', models.TextField(max_length=255)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionspace.patient')),
            ],
        ),
    ]
