# Generated by Django 4.1.7 on 2023-04-05 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminspace', '0003_user_state'),
        ('receptionspace', '0003_visite'),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminspace.collaborateur'),
        ),
    ]
