# Generated by Django 4.1.7 on 2023-04-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionspace', '0004_visite_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visite',
            name='masse',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='visite',
            name='taille',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='visite',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
