# Generated by Django 4.1.7 on 2023-06-29 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminspace', '0003_user_state'),
        ('receptionspace', '0005_alter_visite_masse_alter_visite_taille_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminspace.service'),
        ),
    ]
