# Generated by Django 4.1.7 on 2023-04-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecinespace', '0002_alter_antecedant_anterieur_traitement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenClinique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequence_respiratoire', models.IntegerField(null=True)),
                ('zscrore', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ta', models.CharField(max_length=7, null=True)),
                ('pouls', models.IntegerField(null=True)),
                ('perimetre_cranien', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('perimetre_branchial', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('tuberculose', models.CharField(max_length=5, null=True)),
                ('examen_clinique', models.CharField(max_length=255, null=True)),
                ('diagnostique_retenu', models.CharField(max_length=255)),
                ('autre_pathologie', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenComplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdr_paludisme', models.CharField(max_length=255, null=True)),
                ('goutte_epaisse', models.CharField(max_length=255, null=True)),
                ('milda_12_a_59', models.CharField(max_length=255, null=True)),
                ('remise_milda_12_a_59', models.CharField(max_length=255, null=True)),
                ('cdip_propose', models.CharField(max_length=5, null=True)),
                ('cdip_realise', models.CharField(max_length=5, null=True)),
                ('code_depistage', models.CharField(max_length=255, null=True)),
                ('glycemie_a_jeun', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('glycemie_non_a_jeun', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('autre_examen', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
